
function aFLSJFOINSOFNAOIFNOISANFOIANSFOIAMFOIMAOSIFMAOIMFIOASJFIOANSFIANSFOINASFIONAOSIFNIFNASOIFNAOINFGatherDSAFASMFOINASIFONAIOSFNIOANSFINSIONFIANSFOINAFSOINIOFSANIOFNAOSIFNIAONFSIONASOIFNASIOFNIAF() {
  console.log("DFAS")
  user = document.getElementById('SLKDFNJOSNDJFNMDSKJFGKJSDNJNDFJNSDKJFNDSKJFNDSKJFJKDSNFJSGFDSGDSDSNFuserAKLFNKDSNFJSDNFJSDMFKMSDOIFMDOSIMFOIDMSFOIMDSOIFMDSOFMSDOIFMOIDMFOIMS').value;
  pass = document.getElementById('FASKJFNAOSFNKJASNFKJANSFNASFJNJKFANSJKFNAFKASFNASFNKWAJFNSKJSNFAJNSFJNpassLFMAKLMSFKAMSFLMASFKMASKLFNAKLJSFNJASNFKANSFNASJFNKJASFNKJASNFJANSFN').value;
  console.log(user)
  console.log(pass)
  if (user == "admin") {
    if (pass == "admin") {
        location.href = '/Dash/DashBoard.html';
    }
  }
}
